### ISSUE TITLE
Make `css.Barrier._has_unitary()` return `False`

### ISSUE THREAD

**Issue by perlinm** [SupertechLabs/general-superstaq#118]
... to ensure that `cirq` transformers don't mess with them.  See [comment](https://github.com/SupertechLabs/SuperstaQ/pull/1491#discussion_r932682299)

**Comment by perlinm** [comment]
Also: make sure to make use of this in SuperstaQ after deployment.

**Comment by richrines1** [comment]
@perlinm can i transfer this to the css repo?

**Comment by perlinm** [comment]
Ah yes, my bad.  This should indeed be in `css`
