### ISSUE TITLE
remove cirq warning from check.requirements

### ISSUE THREAD

**Issue by richrines1** [SupertechLabs/general-superstaq#130]
in `css` we usually try to maintain support for a previous version or two of cirq, so the warning is a little misleading

**Comment by vtomole** [comment]
@perlinm Can speak more to this but i think this is fine as the warnings just say that there is indeed a latest version of a package out but there is no requirement to update it. Maybe the warning message being a bit more clear about this should close this issue.

**Comment by richrines1** [comment]
i believe it's just a warning, but i guess imo having a warning at all seems misleading. the warning will never not occur in css because we intentionally don't require the latest version

**Comment by vtomole** [comment]
Good point.

**Comment by perlinm** [comment]
Yep, I'm certainly file with throwing a warning whenever you all think it's reasonable.

**Comment by perlinm** [comment]
Good task for bugsquashing day.  Ping @vtomole @richrines1 about "reasonable" behavior.  My current concern is that the `cirq` warning was added to make `check/requirements.py` yell at us when there's a new `cirq` version that we should support.  If we remove this warning, there would be nothing to (automatically) notify us about a `cirq` update.  Another way of understanding my concern is that there's no way for `check/requirements.py` to know whether the required version of `cirq` is one version behind because (1) we didn't update `requirements.txt` (not a "real" problem, maybe no need for a warning), or (2) we don't support the latest version of `cirq` (bad, should give us a warning).

**Comment by vtomole** [comment]
Maybe we just want to modify the message of the warning to also have a "BTW, this is not too big of a deal, this is just to let you know". Another option is to have a bot create an issue on `css` when there is a new Cirq version.

**Comment by richrines1** [comment]
> Another option is to have a bot create an issue on `css` when there is a new Cirq version.

i really like this idea; imo we should do it for qiskit too

**Comment by perlinm** [comment]
I added #144, but would not consider this issue closed until we have a bot.

**Comment by richrines1** [comment]
somewhat more long-winded notes re: that bot and requirements in `qss`/`css`:

server-side we probably always want to try to be on the most recent versions of cirq and qiskit, but client-side we generally want to specify ranges that (1) include the newest versions, and (2) go as far back as possible without breaking anything. I think this has different implications for the different repos:

**cirq:**
now that cirq is post-beta we should be using a `cirq>=` requirement in `css`, which will ensure that (1) is always satisfied. i don't think we can automate (2), though imo we should maybe be checking it (see https://github.com/SupertechLabs/cirq-superstaq/issues/284). Server-side we should keep using `~=` and just check that we're on the most recent major and minor versions

**qiskit:**
qiskit-terra versions are not always backward-compatible, so sometimes it requires a bit of work/time to update `qss` in order to satisfy (1). So we should definitely be regularly checking it but i'm not sure check/requirements is the right place for it - i  kinda like the idea of making it a github bot/issue (similar to "integration test failed")?

satisfying (2) then generally requires pinning the major & minor versions of qiskit-terra: e.g. if 0.21.3 is the most recent version, 0.20.x will almost definitely break but 0.21.2 might work (but isn't guaranteed to, e.g. 0.21.0 and 0.21.1 will break due to https://github.com/Qiskit/qiskit-terra/issues/8549). So to support the most recent version of qiskit in `qss` we should be requiring `qiskit-terra~=0.21.2`

this is somewhat complicated because multiple versions of the qiskit meta-package sometimes correspond to the same qiskit-terra version. For example qiskit==0.37.2 includes qiskit-terra==0.21.2, but we probably don't want to pin `qiskit~=0.37.2` in `qss` because qiskit==0.38.0 might also include terra==0.21.x. I think this would be solved by including requirements for both; e.g.
```
qiskit>=0.33.0
qiskit-terra~=0.19.1
```
would allow versions of qiskit which include qiskit-terra 0.19.1 or 0.19.2 (i.e. qiskit==0.33.1, 0.34.0, 0.34.1, or 0.34.2)

**Comment by perlinm** [comment]
I understand trying to support as much as possible on the client side, but I am a bit confused.  `check/requirements.py` is only ever run by developers and the server.  @richrines1 your comment makes me think that we should ditch #144, **keep the warnings** (which only pop up for developers + the server), and change this issue (#130) to be something about client-side version support.

Minor note: if we're always comparing against the most recent version (on the server side), then `>=` and `~=` are the same, and using `~=` has the benefit of reduced complexity (same code to check `cirq`, `qiskit,` and `*ss` versions).

**Comment by richrines1** [comment]
happy to discuss irl/on video! a couple quick thoughts:

> `check/requirements.py` is only ever run by developers and the server, so client-side considerations are (I would think) irrelevant for `check/requirements.py`. @richrines1 your comment makes me think that we should ditch #144, **keep the warnings** (which only pop up for developers + the server), and change this issue (#130) to be something about client-side version support

we shouldn't be running checks in the clients if they are irrelevant to the clients. Throwing a warning in `css`/`qss` suggests that something should be changed in those repos, which in this case would be wrong (we *want* the minimum versions of cirq/qiskit to not be the most recent versions). So imo #144 is fine

> Minor note: if we're always comparing against the most recent version (on the server side), then `>=` and `~=` are the same, and using `~=` has the benefit of reduced complexity (same code to check `cirq`, `qiskit`, and `*ss` versions).

server side we should definitely be using `~=`. Client side this can be more restrictive than necessary though, because users often don't have/support the most recent versions of everything (e.g. due to conflicting requirements with other software they're using or weird proxy/security restrictions). So if e.g. css works with any cirq>=0.14.0, we shouldn't limit its requirement to cirq~=1.0.0. I think it's better to drop the check from the clients than to constrain the clients just to simplify a check

**Comment by perlinm** [comment]
Ah I think I was misunderstanding what is meant by "server side" vs. "client side".  Let's take this offline to make clarifications quicker.  I still propose a "breakout meeting" after dev meeting on Thursday.

**Comment by richrines1** [comment]
ah my bad, i definitely could've been more clear. sounds good re: breakout!

**Comment by stephanielee9** [comment]
Closed by https://github.com/SupertechLabs/general-superstaq/pull/144
