### ISSUE TITLE
Expose `dry_run` so examples notebooks can demo the submition of jobs without charging accounts

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/general-superstaq#137]
The easiest solution; which is what I'm preferring right now, is to add a `dry_run` argument to the methods that submit jobs and expose the `dry_run` arguments that exist in the server to the endpoints. @PalashGoiporia can look into this.

_Originally posted by @vtomole in https://github.com/SupertechLabs/cirq-superstaq/issues/263#issuecomment-1154247479_

**Comment by richrines1** [comment]
should be fixed with most recent deployments. dry runs can be instantiated via `service.create_job(..., method="dry-run")` in css and `backend.run(..., method="dry-run")` in qss (cc @PalashGoiporia)

**Comment by stephanielee9** [comment]
`dry-run` is now used wherever it can be
