### ISSUE TITLE
remove `default_target`

### ISSUE THREAD

**Issue by richrines1** [SupertechLabs/general-superstaq#142]
superstaq_client's `default_target` argument is currently useless: it only accepts "qpu" and "simulator", but would need to be a superstaq-formatted target name to work correctly

it would be easy enough to remove this restriction, but imo it makes way more sense to remove `default_target` from `gss` entirely and make it an attribute of `css.Service`. It's only relevant for clients instantiated in `css` - in `qss` it's currently assigned but never used, and doesn't make sense because jobs are created by `qss.SuperstaqBackend`s which already specify a particular target. In `css` it should be similar to choosing a qiskit backend, so that e.g.,

```
service = css.Service(default_target="foo_bar_qpu")

job1 = service.create_job(circuit1, repetitions=100)
job2 = service.create_job(circuit2, repetitions=100)
...
```
would be the same as,
```
service = css.Service()

job1 = service.create_job(circuit1, repetitions=100, target="foo_bar_qpu")
job2 = service.create_job(circuit2, repetitions=100, target="foo_bar_qpu")
...
```
but cleaner and easier to modify in order to use a different target everywhere

@vtomole does this make sense to you?

**Comment by vtomole** [comment]
I agree. This is obsoleted by our superstaq-format and the `options` dict.
