### ISSUE TITLE
include response text from server in some SuperstaQExceptions

### ISSUE THREAD

**Issue by richrines1** [SupertechLabs/general-superstaq#148]
for example, when an endpoint isn't found (e.g. due to an old API version), superstaq returns a response in which `response.text` has a helpful message about updating your client, but `SuperstaqClient` just sees that `response.status_code == requests.codes.not_found` and raises `SuperstaQNotFoundException("SuperstaQ could not find requested resource.")`

**Comment by singular-value** [comment]
Same as https://github.com/SupertechLabs/cirq-superstaq/issues/42 I think
I just moved https://github.com/SupertechLabs/cirq-superstaq/issues/42 from inbox-zero-homework to inbox-zero

**Comment by singular-value** [comment]
Will be resolved by #477
