### ISSUE TITLE
add bot that makes an issue when `cirq` or `qiskit` get updated

### ISSUE THREAD

**Issue by perlinm** [SupertechLabs/general-superstaq#149]
sister issue to #130

**Comment by vtomole** [comment]
We'll use the `>=` property instead. The exception now is [qiskit](https://github.com/SupertechLabs/qiskit-superstaq/blob/cf7aad5d5bc5aafd020de925c6ec1d83d9fabd7f/requirements.txt#L3), but this is a well known [issue](https://github.com/SupertechLabs/SuperstaQ/issues/1204).
