### ISSUE TITLE
Fail to deploy if `daily_integration_test` is failing.

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/general-superstaq#152]
Maybe there is a way for us to script it where it fails to deploy if the integration test has failed.

_Originally posted by @vtomole in https://github.com/SupertechLabs/cirq-superstaq/issues/121#issuecomment-966585810_

**Comment by vtomole** [comment]
This issue is about css and qss. The ss issue is closed by https://github.com/SupertechLabs/SuperstaQ/issues/1105. Leaving open.

**Comment by stephanielee9** [comment]
Overkill
