### ISSUE TITLE
Create extra flag [examples] for qss and css

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/general-superstaq#158]
This will install all the requirements needed to run the notebooks in `examples`

For example

`pip install cirq-superstaq[examples]`

Should install:

```
notebook
pulser
qiskit # only for css
```

@dowusu-antwi Please confirm that this will solve https://github.com/SupertechLabs/cirq-superstaq/issues/136

**Comment by dowusu-antwi** [comment]
> @dowusu-antwi Please confirm that this will solve [SupertechLabs/cirq-superstaq#136](https://github.com/SupertechLabs/cirq-superstaq/issues/136)

Yep, this subsumes https://github.com/SupertechLabs/cirq-superstaq/issues/136.

**Comment by vtomole** [comment]
@perlinm The reason we are doing this flag approach to avoid having an `examples/requirements.txt` in every repo.

**Comment by perlinm** [comment]
I guess I was imagining a situation with `examples` having project sub-directories (such as `examples/qiskit-runtime` or `exmples/qiskit-runtime`), and each project defining its own requirements.  Sounds like that's not what you have in mind though.

**Comment by knsmith** [comment]
https://github.com/SupertechLabs/qiskit-superstaq/pull/245 and https://github.com/SupertechLabs/cirq-superstaq/pull/358 will solve this issue.

**Comment by knsmith** [comment]
https://github.com/SupertechLabs/qiskit-superstaq/pull/245 and https://github.com/SupertechLabs/cirq-superstaq/pull/358 have been merged.
