### ISSUE TITLE
Run coverage checks for python 3.7, 3.9 and 3.10 on Github Actions

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/general-superstaq#165]
To catch Python dependency incompatibilities.

**Comment by knsmith** [comment]
We will also want to add Python 3.11. https://github.com/actions/python-versions/releases

**Comment by knsmith** [comment]
qiskit-superstaq will only run coverage checks for Python 3.7-3.10 until we start using qiskit>=0.37.0

**Comment by knsmith** [comment]
Completed with:
https://github.com/SupertechLabs/general-superstaq/pull/189
https://github.com/SupertechLabs/qiskit-superstaq/pull/266
https://github.com/SupertechLabs/cirq-superstaq/pull/379
https://github.com/SupertechLabs/SuperstaQ/pull/1809
