### ISSUE TITLE
Change examples in `README.md` to something free trial users can run

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/general-superstaq#52]
Right now, the READMEs in `qiskit-superstaq` and `cirq-superstaq` show how to run circuits on `ibmq_qasm_simulator`. The problem is that free trial users are not allowed to do this. We should change the READMEs to run circuits on `ss_qasm_simulator` instead.

**Comment by stephanielee9** [comment]
Have an exception server-side that allows this README to be run

**Comment by vtomole** [comment]
Examples in READMEs still need to be changed to reflect this.

**Comment by stephanielee9** [comment]
https://github.com/SupertechLabs/cirq-superstaq/pull/363 + equivalent qiskit PR closed this
