### ISSUE TITLE
use disallow-any-generics mypy flag

### ISSUE THREAD

**Issue by richrines1** [SupertechLabs/general-superstaq#68]
use `disallow_any_generics = True` to disallow generic annotations like x: list or -> dict instead of x: List[..] or -> Dict[.., ..] (see discussion in https://github.com/SupertechLabs/cirq-superstaq/pull/267)

many of these instances seem to be for json-like dictionaries, which should usually be annotated `Dict[str, Any]` or (ideally) with a `typing.TypeDict`

**Comment by perlinm** [comment]
Possibly a reason to revisit #78 (though we may decide to not do it anyways)

**Comment by vtomole** [comment]
Ran into a couple of issues we need to discuss before we do this.

**Comment by stephanielee9** [comment]
look for typing extensions for numpy (nptyping?)

**Comment by vtomole** [comment]
Done with the merging of https://github.com/SupertechLabs/SuperstaQ/pull/1884
