### ISSUE TITLE
Add integration tests for `.resource_estimate` in css and qss

### ISSUE THREAD

**Issue by singular-value** [SupertechLabs/general-superstaq#88]

**Comment by paaige** [comment]
Relevant PRs in css and qss, respectively: [#304](https://github.com/SupertechLabs/cirq-superstaq/pull/304#pullrequestreview-1044118815), [198](https://github.com/SupertechLabs/qiskit-superstaq/pull/198)

**Comment by vtomole** [comment]
This is already done.and merged. See the linked PRs above,
