### ISSUE TITLE
Rename applications-superstaq to common-superstaq

### ISSUE THREAD

**Issue by singular-value** [SupertechLabs/general-superstaq#93]
This repo has become the shared ground for common code between the clients css and qss. It's no longer just for finance/logistics applications. Name should be changed to common-superstaq.

Libraries like css/qss should use as shorthand: `import common-superstaq as common_ss`

**Comment by stephanielee9** [comment]
Closed with:
https://github.com/SupertechLabs/SupermarQ/pull/41
https://github.com/SupertechLabs/qiskit-superstaq/pull/199
https://github.com/SupertechLabs/cirq-superstaq/pull/306
https://github.com/SupertechLabs/SuperstaQ/pull/1479
https://github.com/SupertechLabs/general-superstaq/pull/109
